FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /hamilton

COPY ["./src/", "src/"]
COPY ["./shared/", "shared/"]
COPY ["./libs/*.nupkg", "libs/"]
COPY ["nuget.config", "nuget.config"]

RUN dotnet restore "src/Hamilton.csproj"

WORKDIR "/hamilton/src"
RUN dotnet build "Hamilton.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Hamilton.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Hamilton.dll"]